services:
  - type: web
    name: neurosalud
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    rootDir: backend
